version: "3.8"

services:
  db:
    image: postgres:13.2
    container_name: db
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
#    networks:
#      - backend
  web:
    build: .
    container_name: web
    restart: always
    ports:
      - "5000:5000"

#  networks:
#    backend:
#      driver: bridge